server:
  port: 10000

spring:
  application:
    name: goods-seata-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
        group: SEATA_GROUP
      config:
        server-addr: 127.0.0.1:8848 #Nacos作为配置中心地址
        file-extension: yaml #指定yaml格式的配置
        group: SEATA_GROUP
#        namespace: 7d8f0f5a-6a53-4785-9686-dd460158e5d4

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudalibaba_seata_goods?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

mybatis-plus:
  #  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml  # 配置 Mapper XML 地址
  typeAliasesPackage: com.xuegao.goodsseatademo.model  # 配置数据库实体包路径

seata:
  enabled: true
  application-id: goods-seata-demo
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    #这里的名字与file.conf中vgroup_mapping.my_test_tx_group = "default"相同
    vgroup-mapping:
      my_test_tx_group: default
      #这里的名字与file.conf中default.grouplist = "127.0.0.1:8091"相同
    grouplist:
      default: 127.0.0.1:8091
  #      disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      namespace:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: "nacos"
      password: "nacos"
