server:
  port: 11000

spring:
  application:
    name: order-seata-demo
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudalibaba_seata_order?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

seata:
  enabled: true
  application-id: order-seata-demo
  tx-service-group: order-seata-demo-seata-group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      namespace:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: "nacos"
      password: "nacos"

